### ISSUE TITLE
Implement additional, technical header properties upon restore

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/kafka-connect-s3#3]
Optionally, restored records should be marked with some technical custom header properties
 
- x-restored=recovery timestamp - inform consumer of the recovery time (just in case they have to be treated differently)
- x-recovery - just informs that the records have been published by a recovery

**Comment by antonioiorfino** [comment]
Now the technical header properties configured during the restore are the following:
- x-old-offset --> Contains the offset backedup on S3
- x-restored --> Contains the timestamp of the restore process running

I have not used the "x-recovery" because if you found the "x-old-offset" and "x-restored" metadata the record it was restored using how procedure.

**Comment by margusja** [comment]
I have issues with this extra headers. At least I think they create problems in my case.
1. Connector backup topic to S3
2. Delete topic and recreate topic with the same config as original one had
3. Restore topics date from S3 - now we have data back and each record has extra header data
4. Now lets start connector backing up topics data to S3
5. Delete topic again and recreate it
6. Try to restore it now from S3
Getting
org.apache.kafka.connect.errors.DataException: The value 32768 is not compatible with the schema Schema{INT64}
	at org.apache.kafka.connect.header.ConnectHeaders.checkSchemaMatches(ConnectHeaders.java:493)
	at org.apache.kafka.connect.header.ConnectHeaders.add(ConnectHeaders.java:127)
	at org.apache.kafka.connect.header.ConnectHeaders.add(ConnectHeaders.java:133)
	at ch.tbd.kafka.backuprestore.restore.kafkaconnect.RestoreSourceTask.lambda$headerList$0(RestoreSourceTask.java:191)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at ch.tbd.kafka.backuprestore.restore.kafkaconnect.RestoreSourceTask.headerList(RestoreSourceTask.java:188)
	at ch.tbd.kafka.backuprestore.restore.kafkaconnect.RestoreSourceTask.restore(RestoreSourceTask.java:142)
	at ch.tbd.kafka.backuprestore.restore.kafkaconnect.RestoreSourceTask.poll(RestoreSourceTask.java:164)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

32768  - unsigned integer positive range limt? 

Any hints?

Br,
Margus
